require 'kuma-bot/commands/giphy'
require 'kuma-bot/commands/calc'
require 'kuma-bot/commands/google'
require 'kuma-bot/commands/fxrate'
require 'kuma-bot/commands/about'
require 'kuma-bot/commands/unknown'
require 'kuma-bot/commands/help'
require 'kuma-bto/commands/translate'
